# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de7252caf6704adc995b52df6b5e6173e1d97ebebb83dd8732fb0849d6b5bd02949a9ff12f29d361f24440b47592f72bb5cd5dcc5ae44060e27b7adfe83c867

test:
  secret_key_base: 817b46a9a1da26bb5282e1ee755d50cdfae54ffac92deda61a95bfb216243f0ab43a497158a4fe8a1f5414fd816158c3fb06154a62bdec0b05e9183de9c574d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
